apiVersion: 1

datasources:
  - name: TeslaMate
    uid: TeslaMate
    type: postgres
    url: $DATABASE_HOST:$DATABASE_PORT
    user: $DATABASE_USER
    access: proxy
    basicAuth: false
    isDefault: true
    secureJsonData:
      password: $DATABASE_PASS
    jsonData:
      postgresVersion: 1500
      sslmode: ${DATABASE_SSL_MODE:-disable}
      database: $DATABASE_NAME
    editable: true
